### ISSUE TITLE
dragging the slider causes whole page to jump to top

### ISSUE THREAD

**Issue by brendano** [AbeHandler/rookie#156] opened 2016-02-29 00:24 UTC
if you first scroll down then try to manipulate the slider, the page scroll jumps to top.  this feels symptomatic of something weird ...

[screencast zip file](https://github.com/AbeHandler/rookie/files/150214/Untitled.zip)

**Comment by AbeHandler** [comment] 2016-02-29 13:39
@brendano I think this is a dupe of #158. I *think* the issue was not about the scrolling down, but instead came from 2 separate calls from Chart.jsx to UI.jsx updating start and end date state vars separately. I added a new method that updated them both at the same time which seems to fix the issue.

**Closed by AbeHandler** 2016-02-29 13:39 UTC

**Comment by brendano** [comment] 2016-02-29 23:08
works very nicely now
