### ISSUE TITLE
no red timeline, OWS / gawker

### ISSUE THREAD

**Issue by brendano** [AbeHandler/rookie#205] opened 2016-04-14 21:26 UTC
Q=occupy wall street
F=Brooklyn Bridge
corpus=gawk

text says 10 documents in (Q&F) but don't see any red timeline.  I think the y-axis scale is small enough that it should be visible... might be relate to another bug we've been posting about.

![screen shot 2016-04-14 at 5 25 21 pm](https://cloud.githubusercontent.com/assets/1677/14544224/11d640aa-0266-11e6-860f-4f68a99af17a.png)

**Comment by AbeHandler** [comment] 2016-04-14 23:37
yeah I have noticed this too. Will take a look.

**Comment by AbeHandler** [comment] 2016-04-21 17:11
Bug from aliasing + facets? A good place to look.

**Comment by AbeHandler** [comment] 2016-07-01 07:21
caused by some truly terrible code i wrote it October. should be fixed now.

**Closed by AbeHandler** 2016-07-01 07:21 UTC
