### ISSUE TITLE
Punctuation issues

### ISSUE THREAD

**Issue by myersnews** [AbeHandler/rookie#55] opened 2015-12-16 23:02 UTC
http://54.213.128.229/facets?q=Mitch%20Landrieu

click 2011 blue dot for Dept of Justice. Note the missing apostrophes in the snippet. Also notice that ther are stray spaces before the commas. 

(can't deal with the stray byline text because that is an artifact of a prior migration of the site, where the byline is duplicated in the body text itself.)

**Comment by brendano** [comment] 2015-12-31 04:29
symptom of nlp preproc pipeline and issues with passing through original text.  easy hack will be to heuristically un-tokenize sentences.  but better to put original sentence texts into the doc store.  either postgres or whoosh store=True. could represent sentence text as a string, or alternatively, from the original text offsets (get them from corenlp's start of first token and end of last token in sentence) against the original full-doc text.  (where "original" means, after HTML cleaning.)

**Comment by AbeHandler** [comment] 2016-01-27 13:39
@myersnews  1.2.7.16: snippets: need space after periods. need apostrophes. delete spaces before commas. and you’re still missing quotes. All of those make it hard to comprehed the snippets and will reduce the likelihood that people will be able to use rookie to understand the subject in the user test.

**Comment by brendano** [comment] 2016-01-27 15:20
yeah i noticed these issues are still there. lmk if want a sketch of how to arrange data structures that will solve this

**Comment by AbeHandler** [comment] 2016-01-27 15:39
@brendano yah it would be great to talk this over. moving this to minimumviable

**Comment by brendano** [comment] 2016-02-16 16:19
at least some issues are caused by misprocessing of quotes.
i saw the attached "Donald Trumps" on a recent issue

<img width="866" alt="screen shot 2016-02-16 at 11 14 37 am" src="https://cloud.githubusercontent.com/assets/1677/13082400/908cb640-d49e-11e5-85e3-765b4208addd.png">

i grepped the corpus and think it corresponds to this:

    Donald Trump’s Birth Certificate Is Clearly a Fake

default corenlp settings process it just fine too:

        {u'sentences': [{u'tokens': [u'Donald', u'Trump', u"'s", u'Birth', u'Certificate', u'Is', u'Clearly', u'a', u'Fake'] ....

there's a deeper issue in the pipeline.  maybe headlines are run through a heuristic tokenizer or something?  or something funny happens with unicode during preprocessing?  the input data isn't processed as utf8 maybe?

**Closed** 2016-10-27 04:13 UTC
